# Generated by Django 3.2.4 on 2021-07-04 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
