# Generated by Django 3.2.4 on 2021-07-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
