# Generated by Django 3.2.4 on 2021-07-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '__first__'),
        ('likes', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='users', through='likes.Like', to='user.User'),
        ),
    ]
